### PR TITLE
Submit yespornplease.adult

### PR DESCRIPTION
**Pull request by Najoj**
yespornplease.com was in the files, but not with .adult TLD.

### CODE REVIEW

**Comment by Najoj** [comment]
I am not sure what you are asking.

**Comment by Najoj** [comment]
Should the url be in Mobile as well? Easily fixed.

**Comment by spirillen** [comment]
Super, I'll hit the merge later when my PR <https://github.com/Clefspeare13/pornhosts/pull/138>/branch is done

**Comment by spirillen** [comment]
`www.$domain` redirects to `$domain`

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +60 |  |  | yespornplease.adult | 1 | image | `https://yespornplease.adult/wp-content/uploads/2019/02/cropped-icon-32x32.jpg` |
| +60 |  |  | yespornplease.adult | 1 | image | `https://yespornplease.adult/wp-content/uploads/2019/02/cropped-icon-192x192.jpg` |
| +59 |  |  | yespornplease.adult | 3 | script | `https://g2178927685.co/gl?id=-MD7_ko5Zp8Nl9Gduv-x&refurl=&winurl=https%3A%2F%2Fyespornplease.adult%2F` |
| +59 |  |  | yespornplease.adult | 1 | image | `https://yespornplease.adult/` |
| +59 |  |  | yespornplease.adult | 1 | script | `https://yespornplease.adult/wp-content/plugins/rocket-lazy-load/assets/js/12.0/lazyload.min.js` |
| +59 |  |  | yespornplease.adult | 1 | script | `https://yespornplease.adult/wp-includes/js/wp-embed.min.js?ver=5.0.10` |
| +59 |  |  | yespornplease.adult | 1 | script | `https://yespornplease.adult/wp-content/themes/retrotube/assets/js/skip-link-focus-fix.js?ver=1.0.0` |
| +59 |  |  | yespornplease.adult | 1 | script | `https://yespornplease.adult/wp-content/themes/retrotube/assets/js/main.js?ver=1.2.5` |
| +59 |  |  | yespornplease.adult | 1 | script | `https://yespornplease.adult/wp-content/themes/retrotube/assets/js/jquery.bxslider.js?ver=4.2.12` |
| +59 |  |  | yespornplease.adult | 1 | script | `https://yespornplease.adult/wp-content/themes/retrotube/assets/js/navigation.js?ver=1.0.0` |
| +59 |  |  | yespornplease.adult | 1 | script | `https://yespornplease.adult/wp-includes/js/wp-emoji-release.min.js?ver=5.0.10` |
| +59 | \|\|getclicky.com^$3p | -- | yespornplease.adult | 3 | script | `https://static.getclicky.com/js` |
| +59 |  |  | yespornplease.adult | 1 | image | `https://yespornplease.adult/wp-content/themes/retrotube/assets/img/px.gif` |
| +59 |  |  | yespornplease.adult | 1 | script | `https://yespornplease.adult/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1` |
| +59 |  |  | yespornplease.adult | 1 | script | `https://yespornplease.adult/wp-includes/js/jquery/jquery.js?ver=1.12.4` |
| +59 |  |  | yespornplease.adult | 1 | css | `https://yespornplease.adult/wp-content/themes/retrotube/ypp.css?ver=1625317870` |
| +59 | \|\|getclicky.com^$3p | -- | yespornplease.adult | 3 | script | `https://static.getclicky.com/js` |
| +59 | \|\|googleapis.com^$important | -- | yespornplease.adult | 3 | css | `https://fonts.googleapis.com/css?family=Open+Sans` |
| +58 |  |  | yespornplease.adult | 1 | doc | `https://yespornplease.adult/` |
| +58 |  |  | `www.yespornplease.adult` | 1 | doc | `https://www.yespornplease.adult/` |
| +0 |  |  | yespornplease.adult | 3 | media | `https://1480222913.rsc.cdn77.org/` | `aliasURL=https://cdn77-pic.xvideos-cdn.com/videos/videopreview/bd/46/54/bd46544790796338811edf4a4122fb16_169.mp4` |
| +0 |  |  | yespornplease.adult | 3 | media | `https://cdn77-pic.xvideos-cdn.com/videos/videopreview/bd/46/54/bd46544790796338811edf4a4122fb16_169.mp4` |
| +0 |  |  | yespornplease.adult | 3 | media | `https://1480222913.rsc.cdn77.org/` | `aliasURL=https://cdn77-pic.xvideos-cdn.com/videos/videopreview/bd/46/54/bd46544790796338811edf4a4122fb16_169.mp4` |
| +0 |  |  | yespornplease.adult | 3 | media | `https://cdn77-pic.xvideos-cdn.com/videos/videopreview/bd/46/54/bd46544790796338811edf4a4122fb16_169.mp4` |
| +0 |  |  | yespornplease.adult | 3 | media | `https://cds.g9c9c3d5.hwcdn.net/` | `aliasURL=https://img-hw.xvideos-cdn.com/videos/videopreview/b3/7d/d8/b37dd89e69dff2a672a90c3826e8551f_169.mp4` |
| +0 |  |  | yespornplease.adult | 3 | media | `https://img-hw.xvideos-cdn.com/videos/videopreview/b3/7d/d8/b37dd89e69dff2a672a90c3826e8551f_169.mp4` |
</details>

**Comment by spirillen** [comment]
This is to no fault of @Najoj that I "just" closes this PR, but it is simply way easier just redo this one by script.

**Pull request closed without merging**
