### PR TITLE
cheap.porn

### PR DESCRIPTION
**Pull request by DaniV5**
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

```python
cheap.porn
```

## Screenshots

<details><Summary>Screenshot required</summary>

cheapporn1
cheapporn2
cheapporn3

</details>

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [x] Added ScreenDump for prove of False Positive

### Todo
- [ ] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

### CODE REVIEW

**Review by spirillen — CHANGES_REQUESTED** [review]
This commit deletes 

```
www.bustybloom.com
contenta.bustybloom.com
content0.bustybloom.com
content2.bustybloom.com
content3.bustybloom.com
content4.bustybloom.com
content5.bustybloom.com
content6.bustybloom.com
```

**Comment by DaniV5** [comment]
i don't know why

**Comment by spirillen** [comment]
> i don't know why

Becouse you don't do a 
```shell
git pull || git pull --rebase
```

Before editing the hosts file.... so you don't get my submission in, and merges from master (this repo)

**Comment by DaniV5** [comment]
i'm using the site
not the program

**Comment by spirillen** [comment]
In this case you would do something like 

```shell
git checkout DaniV5:patch-84
git pull --rebase
```

Or click on the `Resolve conflict`

image

**Review by lobo831 — APPROVED** [review]

**Pull request closed without merging**
