### PR TITLE
femefun.com

### PR DESCRIPTION
**Pull request by DaniV5**
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

```python
femefun.com
s4.femefun.com
```

## Screenshots

<details><Summary>Screenshot required</summary>

femefun1
femefun2

</details>

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [x] Added ScreenDump for prove of False Positive

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [x] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

### CODE REVIEW

**Review by spirillen — CHANGES_REQUESTED** [review]
Please rebase as this would delete `tubevideos.pw` and `www.tubevideos.pw`

**Comment by DaniV5** [comment]
what the hell is happening

**Comment by spirillen** [comment]
Read my comment in other thread :smiley:

**Comment by DaniV5** [comment]
go to the darned irc

**Comment by spirillen** [comment]
> go to the darned irc

Nope, it midnight here, that will have to wait until tomorrow :zzz: :sleepy:

**Comment by DaniV5** [comment]
so it will have to wait
because i don't know how to fix it

**Comment by spirillen** [comment]
But write you question on IRC so you don't forget it... it's open on the other PC

**Comment by spirillen** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +104 |  |  | femefun.com | 1 | media | `https://s4.femefun.com/remote_control.php?time=1602356038&cv=df36161bc2554c3a7cbfce9543460033&lr=0&cv2=bff57327ad08770ee12d0b61c5615d7a&file=%2Fcontents%2Fvideos%2F42000%2F42402%2F42402_short_preview.mp4&cv3=9eb111fd3c8412600e04db769cb57eb1&cv4=cb296f46661041d1a2cd1dae58539859` |
| +104 |  |  | femefun.com | 1 | media | `https://femefun.com/get_file/1/2cfe6087fe134d0fc97539293b47716e/42000/42402/42402_short_preview.mp4/` |
| +100 |  |  | femefun.com | 1 | media | `https://s4.femefun.com/remote_control.php?time=1602356038&cv=df36161bc2554c3a7cbfce9543460033&lr=0&cv2=bff57327ad08770ee12d0b61c5615d7a&file=%2Fcontents%2Fvideos%2F42000%2F42402%2F42402_short_preview.mp4&cv3=9eb111fd3c8412600e04db769cb57eb1&cv4=cb296f46661041d1a2cd1dae58539859` |
| +100 |  |  | femefun.com | 1 | media | `https://femefun.com/get_file/1/2cfe6087fe134d0fc97539293b47716e/42000/42402/42402_short_preview.mp4/` |
| +69 | &action=js_stats& | -- | femefun.com | 1 | image | `https://femefun.com/?mode=async&action=js_stats&rand=1602356523653` |
| +69 |  |  | femefun.com | 1 | image | `https://femefun.com/favicon.ico` |
| +69 | \|\|d261u4g5nqprix.cloudfront.net^ | -- | femefun.com | 3 | script | `https://d261u4g5nqprix.cloudfront.net/?qngud=861703` |
| +69 | \|\|fonts.gstatic.com^$important | -- | femefun.com | 3 | font | `https://fonts.gstatic.com/s/roboto/v16/d-6IYplOFocCacKzxwXSOFtXRa8TVwTICgirnJhmVJw.woff2` |
| +69 | \|\|fonts.gstatic.com^$important | -- | femefun.com | 3 | font | `https://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2` |
| +69 | \|\|wpush.org^$3p | -- | femefun.com | 3 | script | `https://sw.wpush.org/script/main.js?promo=19865&tcid=2145&src=1010490020` |
| +69 |  |  | femefun.com | 1 | script | `https://femefun.com/static/js/theme.min.js?v=1.1` |
| +69 |  |  | femefun.com | 1 | script | `https://femefun.com/static/js/vendors.min.js?v=1.1` |
| +69 |  |  | femefun.com | 1 | script | `https://femefun.com/js/main.min.js?v=1.1` |
| +69 | \|\|d261u4g5nqprix.cloudfront.net^ | -- | femefun.com | 3 | script | `https://d261u4g5nqprix.cloudfront.net/?qngud=861703` |
| +69 | /sw.js$script | -- | femefun.com | 1 | script | `https://femefun.com/sw.js` |
| +69 | ##+js(noeval) |  | femefun.com |  | dom | `https://femefun.com/` |
| +69 | ##+js(abort-on-property-write, __htapop) |  | femefun.com |  | dom | `https://femefun.com/` |
| +69 |  |  | femefun.com | 1 | doc | `https://femefun.com/` |
| +68 |  |  | `www.femefun.com` | 1 | doc | `http://www.femefun.com/` |
| +64 |  |  | femefun.com | 1 | image | `https://femefun.com/favicon.ico` |
| +63 | &action=js_stats& | -- | femefun.com | 1 | image | `https://femefun.com/?mode=async&action=js_stats&rand=1602356517708` |
| +63 | \|\|d261u4g5nqprix.cloudfront.net^ | -- | femefun.com | 3 | script | `https://d261u4g5nqprix.cloudfront.net/?qngud=861703` |
| +63 |  |  | femefun.com | 1 | font | `https://femefun.com/static/fonts/light-black/icomoon.ttf?5o5hn8` |
| +63 | \|\|fonts.gstatic.com^$important | -- | femefun.com | 3 | font | `https://fonts.gstatic.com/s/roboto/v16/d-6IYplOFocCacKzxwXSOFtXRa8TVwTICgirnJhmVJw.woff2` |
| +63 | \|\|fonts.gstatic.com^$important | -- | femefun.com | 3 | font | `https://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2` |
| +63 | \|\|wpush.org^$3p | -- | femefun.com | 3 | script | `https://sw.wpush.org/script/main.js?promo=19865&tcid=2145&src=1010490020` |
| +63 |  |  | femefun.com | 1 | script | `https://femefun.com/static/js/theme.min.js?v=1.1` |
| +63 |  |  | femefun.com | 1 | script | `https://femefun.com/static/js/vendors.min.js?v=1.1` |
| +63 |  |  | femefun.com | 1 | script | `https://femefun.com/js/main.min.js?v=1.1` |
| +63 | \|\|d261u4g5nqprix.cloudfront.net^ | -- | femefun.com | 3 | script | `https://d261u4g5nqprix.cloudfront.net/?qngud=861703` |
| +63 | /sw.js$script | -- | femefun.com | 1 | script | `https://femefun.com/sw.js` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/54000/54195/320x180/1.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/54000/54190/320x180/4.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/54000/54193/320x180/2.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/54000/54164/320x180/2.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/54000/54161/320x180/1.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/54000/54095/320x180/5.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/54000/54128/320x180/3.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/54000/54116/320x180/1.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/54000/54118/320x180/1.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/54000/54115/320x180/1.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/54000/54064/320x180/1.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/54000/54035/320x180/1.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/54000/54108/320x180/1.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/53000/53471/320x180/1.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/23000/23510/320x180/5.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/47000/47462/320x180/1.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/41000/41789/320x180/1.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/36000/36646/320x180/14.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/contents/videos_screenshots/42000/42402/320x180/1.jpg` |
| +63 |  |  | femefun.com | 1 | image | `https://femefun.com/static/images/logo.png?2` |
| +63 | ##+js(noeval) |  | femefun.com |  | dom | `https://femefun.com/` |
| +63 | ##+js(abort-on-property-write, __htapop) |  | femefun.com |  | dom | `https://femefun.com/` |
| +62 |  |  | femefun.com | 1 | doc | `https://femefun.com/` |
| +62 |  |  | femefun.com | 1 | doc | `http://femefun.com/` |
| +60 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoxOTI3NjU1NDcxLCJ0IjoxNjAyMzU2NDk0fQ%3D%3D--7669182e497e99bf75adc19a87330ed36be68c47db09c870de9a5a928a8b54a1&shared=true |
| +42 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +41 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +35 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +35 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +22 |  |  | github.com | 0,3 | script | `https://github.githubassets.com/assets/socket-worker-2219cd37.js` |
| +22 |  |  | github.com | 0,1 | script | `https://github.com/socket-worker.js` |
| +20 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +18 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +17 | \|\|github.com/_alive$xmlhttprequest,important | -- | github.com | 0,1 | xhr | `https://github.com/_alive` |
| +0 | \|\|alive.github.com^$websocket,important | -- | github.com | 0,1 | websocket | wss://alive.github.com/_sockets/u/44526987/ws?session=eyJ2IjoiVjMiLCJ1Ijo0NDUyNjk4NywicyI6NTkzMjE0ODQxLCJjIjoyMTk1NTAxMDM5LCJ0IjoxNjAyMzU2Mzc4fQ%3D%3D--79fe58a971c00fe8eb53cb45d806c0af062243749331f207de173da72fcc1542&shared=true |
</details>

**Pull request closed without merging**
