### PR TITLE
av4.xyz

### LINKED ISSUE #359: av4.xyz
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
av4.xyz
www.av4.xyz
```

## Content sources

(Please see #35)

```python
av.av4.xyz
1080p.av4.xyz
jp.av4.xyz
en.av4.xyz
cn.av4.xyz
de.av4.xyz
kr.av4.xyz
ru.av4.xyz
th.av4.xyz
es.av4.xyz
ab.av4.xyz
```

## External sources (reference)

```python
anime-tube.pw
www.anime-tube.pw
```

## Screenshots

<details><Summary>Screenshot required</summary>

image
image
image

</details>

### All Submissions:
- [x] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [x] Added a Screenshot for prove of Adult contents

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

### PR DESCRIPTION
**Pull request by mateusfg7**
I believe this domain is an Adult(-related) domain --> that have to be blocked as..

## Domains
Only add the needed one See also #12

```python
av4.xyz
www.av4.xyz
```

## Content sources

(Please see #35)

```python
av.av4.xyz
1080p.av4.xyz
jp.av4.xyz
en.av4.xyz
cn.av4.xyz
de.av4.xyz
kr.av4.xyz
ru.av4.xyz
th.av4.xyz
es.av4.xyz
ab.av4.xyz
```

## External sources (reference)

```python
anime-tube.pw
www.anime-tube.pw
```

## Screenshots

<details><Summary>Screenshot required</summary>

image
image
image

</details>

### All Submissions:
- [x] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open
	[Merge Requests (MR)](../merge_requests) or [Issues](../issues) for
	the same update/change?
- [x] Added ScreenDump for prove of False Positive

### Todo
- [x] Added to [Source file](submit_here/hosts.txt)?
- [ ] Added to the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) (@spirillen)

---

- close #359

### CODE REVIEW

**Comment by spirillen** [comment]
Hey @mateusfg7 Your submission nor you are forgotten, just been busy setting up Gitlab on mypdns.org as Phabricator have stop further coding on the code base

**Review by spirillen — APPROVED** [review]

**Review by spirillen — COMMENTED** [review]
They are all redirecting to `*.nyuu.info`  where * is one of the prefixes {av-jp}

But I don't know if this is related to my IP address location.

Is it possible you can append a screenshot that shows you stays on av4.xyz in your location??

**Comment by spirillen** [comment]
Have been digging a bit further in this. it turns out to be `js.gazo.space` and `jpg4.pw` if we block those we actually blocks a hole lot of porn domains in two steps

<details><summary>Logger output (Blocking js.gazo.space)</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 |  |  | cndata.jpg4.pw | 1 | image | `http://cndata.jpg4.pw/favicon.ico` |
| +2 | \|\|googletagmanager.com^ | -- | cndata.jpg4.pw | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-620120-3` |
| +2 | \|\|cdn.jsdelivr.net/npm/yandex-metrica-watch/watch.js | -- | cndata.jpg4.pw | 3 | script | `https://cdn.jsdelivr.net/npm/yandex-metrica-watch/watch.js` |
| +2 |  |  | cndata.jpg4.pw | 3 | script | `https://cdnjs.cloudflare.com/ajax/libs/nosleep/0.11.0/NoSleep.min.js` |
| +2 | \|\|googleapis.com^$important | -- | cndata.jpg4.pw | 3 | script | `https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js` |
| +2 | \|\|googleapis.com^$important | -- | cndata.jpg4.pw | 3 | script | `https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js` |
| +2 |  |  | cndata.jpg4.pw | 3 | script | `https://js.gazo.space/index.php?js=jpg4&aaa2` |
| +2 |  |  | cndata.jpg4.pw | 3 | script | `https://js.gazo.space/index.php?js=very` |
| +1 | /favicon.ico$image,3p,domain=~streameast.live\|~apple.com\|~douban.com\|~bahn.de\|~winfuture.de\|~bt.com\|~ebay.com.au\|~ebay.com\|~ebay.co.uk\|~go.com\|~github.com\|~microsoft.com\|~stackexchange.com\|~stackoverflow.com\|~askubuntu.com\|~reddit.com\|~4chan.org\|~twitter.com\|~live.com\|~espn.com\|~yahoo.com\|~jit.si | -- | cndata.jpg4.pw | 3 | image | `http://en.av4.xyz/favicon.ico` |
| +1 |  |  | cndata.jpg4.pw | 1 | doc | `http://cndata.jpg4.pw/index.php?oldhot=all` |
| +1 | /favicon.ico$image,3p,domain=~streameast.live\|~apple.com\|~douban.com\|~bahn.de\|~winfuture.de\|~bt.com\|~ebay.com.au\|~ebay.com\|~ebay.co.uk\|~go.com\|~github.com\|~microsoft.com\|~stackexchange.com\|~stackoverflow.com\|~askubuntu.com\|~reddit.com\|~4chan.org\|~twitter.com\|~live.com\|~espn.com\|~yahoo.com\|~jit.si | -- | en.av4.xyz | 3 | image | `https://twitter.com/favicon.ico` |
| +1 | \|\|js.gazo.space/index.php?js=*&advertisement&$script | -- | en.av4.xyz | 3 | script | `https://js.gazo.space/index.php?js=av4&advertisement&` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://dm0qx8t0i9gc9.cloudfront.net/thumbnails/video/H5BOVymHiplawzr0/videoblocks-a-young-father-spends-time-with-his-little-daughter-father-and-child-sit-on-the-bed-at-home-and-play-parent-child-friendship_hllbqfyzm_thumbnail-1080_01.png` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.new-porn.club/images/thumbs/a/13617/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://blog-imgs-105.fc2.com/a/v/s/avstory/h02966.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://static.thisav.com/images/videothumbs/104936-1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://images.interracialfuckfan.com/wp-content/uploads/2019/05/angelemily.jpg---16185610` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://fi1-ph.ypncdn.com/videos/202011/25/373570052/original/8(m=e8KSKgaaaa)(mh=OswT0rW8Dt2BnXxF).jpg` |
| +1 |  |  | en.av4.xyz | 1 | image | `http://en.av4.xyz/poster/://poster.nakadashi.pw/poster/s://www.lanewgirl.com/wp-content/uploads/2019/12/lily-adams-porn-audition-casting-couch-1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.xlesbian.club/images/thumbs/a/21591/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://vl9x.com/wp-content/uploads/i/tong-hop-clip-thu-dam-gai-moi-lon-cute.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://dm0qx8t0i9gc9.cloudfront.net/thumbnails/video/HJpjKMlmgiw923pte/videoblocks-little-girl-on-the-floor-at-home-trying-moms-red-high-heel-shoes_hqwvtwqhbe_thumbnail-1080_01.png` |
| +1 |  |  | en.av4.xyz | 1 | image | `http://en.av4.xyz/poster/://poster.nakadashi.pw/poster/s://www.lanewgirl.com/wp-content/uploads/2019/02/nikki-peach-porn-audition-casting-couch-2.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://imagecdn.clips4sale.com/accounts99/91531/clip_images/gg_gif.gif` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://static.thisav.com/images/videothumbs/452013-1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i1.wp.com/livedoor.blogimg.jp/onaking072-sp8rms00/imgs/2/1/21a66e0c.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://img1.taslgs.com/upload/vod/2020-09/2020-09-09/2020090911.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.xlesbian.club/images/thumbs/a/25019/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://thumbs.theync.com/thumbs/6/9/6/7/9/6967965ac6881286ce9.mp4/6967965ac6881286ce9.mp4-3.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://img.redwap-cdn.com/269/269229/269229_320x180.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://static.thisav.com/images/videothumbs/315096-1.jpg` |
| +1 |  |  | en.av4.xyz | 1 | image | `http://en.av4.xyz/poster/://poster.nakadashi.pw/poster/s://www.lanewgirl.com/wp-content/uploads/2020/03/aria-banks-porn-audition-casting-couch-1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i1.wp.com/i.ibb.co/xGwr4CV/shishunki-sex-ep2.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://di1-ph.ypncdn.com/videos/202101/08/381348062/original/16(m=e8KSKgaaaa)(mh=gJie_LxYq5MsqAZM).jpg---20180946` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.xlesbian.club/images/thumbs/a/23605/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://static.thisav.com/images/videothumbs/99967-1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://dm0qx8t0i9gc9.cloudfront.net/thumbnails/video/rZJIMvhmliwmde8a6/videoblocks-children-playing-doctor-and-patient-kids-playing-doctor-in-playroom-or-kindergarten_rv1t7wcan_thumbnail-1080_01.png` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://s5.bitporno.com/thumb/0/200926/320GJ41Q92V9CH0XC6ZQ6.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://img.redwap-cdn.com/172/172314/172314_320x180.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://static.thisav.com/images/videothumbs/559891-1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://static.thisav.com/images/videothumbs/294520-1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://pic.cnsypic.com/Miyagc-pic/AA202C8F04F731EA.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://www.art-nudes.com/wp-content/uploads/2018/10/leonie-a.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.xlesbian.club/images/thumbs/a/24157/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://xnhentai.com/wp-content/uploads/2020/09/0012001023123123.png` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://extra.famegirls.net/content2/8101/thumb100.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://wild-kitty.net/video/vid175.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://img1.xszcdn.com/upload/vod/20201022-1/3b5f621adb6b34672f6d8e19418b81d0.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://extra.famegirls.net/content2/8031/thumb100.jpg` |
| +1 |  |  | en.av4.xyz | 1 | image | `http://en.av4.xyz/poster/s://www.lanewgirl.com/wp-content/uploads/2020/10/jessae-rosae-porn-audition-casting-couch-3.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://static.thisav.com/images/videothumbs/312370-1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://dm0qx8t0i9gc9.cloudfront.net/thumbnails/video/GTYSdDW/cheerful-little-girl-is-having-fun-in-the-outdoors-swimming-pool-slow-motion-240-fps-child-is-jumping-and-playing-in-the-water-on-a-warm-summer-day-happy-childhood-concept_epmamzneox_thumbnail-1080_01.png` |
| +1 | \|\|celebjihad.com^$3p | -- | en.av4.xyz | 3 | image | `https://celebjihad.com/wp-content/uploads/2019/09/t_margot_robbie_nude_anal_sex_harley_quinn2.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://pornolomka.click/uploads/posts/2017-12/medium/1514455311_00-00-02.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.xlesbian.club/images/thumbs/a/28008/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.xlesbian.club/images/thumbs/a/1327/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.xlesbian.club/images/thumbs/a/8716/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://wild-kitty.net/video/vid179.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://static.espreso.tv/uploads/article/2450369/images/im578x383-capa-4.png` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://www.art-nudes.com/wp-content/uploads/2018/10/kay-j.jpg` |
| +1 |  |  | en.av4.xyz | 1 | image | `http://en.av4.xyz/poster/://poster.nakadashi.pw/poster/s://www.lanewgirl.com/wp-content/uploads/2019/04/kate-bloom-teen-pornstar-casting-audition-2.jpg` |
| +1 |  |  | en.av4.xyz | 1 | image | `http://en.av4.xyz/poster/://poster.nakadashi.pw/poster/s://www.lanewgirl.com/wp-content/uploads/2017/11/hanna-hays-porn-audition-casting-couch-4.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://static.thisav.com/images/videothumbs/319154-1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://cdn.hotscope.tv/files/thumbnail/4lfMzwN0G.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://fi1-ph.ypncdn.com/videos/201610/21/93662531/original/2(m=e8KSKgaaaa)(mh=ieHVNAtGQyQGsCXC).jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://st.peppahub.com/thumbs/e4/41/e441919f9e8979da45af253a29296509.0.jpg` |
| +1 |  |  | en.av4.xyz | 1 | image | `http://en.av4.xyz/poster/://poster.nakadashi.pw/poster/s://www.lanewgirl.com/wp-content/uploads/2018/02/kylie-martin-porn-audition-casting-couch-7.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://rapefilms.net/tb/mansion-y-lady.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://thumbs.theync.com/thumbs/4/9/6/6/8/4966835c5224c4b5c2a.wmv/4966835c5224c4b5c2a.wmv-7b.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://www.jyukujyomanko.com/wordpress/wp-content/uploads/2021/04/e38090e5808be4babae692aee5bdb1e38091e4b88de580absexe381a7e3838fe383a1e692aee3828ae38199e3828be6b7abe4b9b1e5a5a5e38195e381bee38090.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://rapefilms.net/tb/young-lover-for-wife.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://xxxpornopics.b-cdn.net/vlcsnap-2020-01-09-23h36m28s755.png` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://s1.bitporno.com/thumb/0/201013/491GJNWEHWF2QZHKXFBUR.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.xlesbian.club/images/thumbs/a/39236/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://static.thisav.com/images/videothumbs/70542-1.jpg` |
| +1 |  |  | en.av4.xyz | 1 | image | `http://en.av4.xyz/poster/://poster.nakadashi.pw/poster/s://www.lanewgirl.com/wp-content/uploads/2021/03/cierra-bell-porn-audition-casting-couch-1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://static.thisav.com/images/videothumbs/480729-1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://st.javvhub.com/thumbs/9e/d9/9ed9d4deab1f747fa6273936faf7ed6f.0.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://okashik.atype.jp/images/103-mbr-083/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://panchirasakasa.xyz/wp-content/uploads/2021/05/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88-2021-05-29-12.40.21.jpg` |
| +1 |  |  | en.av4.xyz | 1 | image | `http://en.av4.xyz/poster/://poster.nakadashi.pw/poster/s://www.lanewgirl.com/wp-content/uploads/2018/10/lindsey-cruz-porn-audition-casting-couch-2.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://s1.bitporno.com/thumb/0/200930/802GJ989LJ806BBBDYYSS.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://cdn.thaixtube.com/thumbs_173/1c/112790445/b_orig.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://static.thisav.com/images/videothumbs/96333-1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://aphroditeporntube.com/media/videos/tmb/30180/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://fi1.ypncdn.com/201712/02/14211425/original/8/tight-pussy-teen-marusya-mechta-8(m=eaAaaEPbaaaa).jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://rapefilms.net/tb/french-vacansion.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://ytboob.b-cdn.net/wp-content/uploads/2020/09/iouxz7.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://www.clips4sale.com/Assets/Static/img/c4sFixedLogo.png` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://6.cdnxsalty9.com:8081/3/2/b/32b53eb9-d8c9-4014-aa06-3f07dcb9b582.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.xlesbian.club/images/thumbs/a/19819/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://cdn.hotscope.tv/files/thumbnail/capture(1560).jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://static.thisav.com/images/videothumbs/270103-1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://dm0qx8t0i9gc9.cloudfront.net/thumbnails/video/HJpjKMlmgiw923pte/videoblocks-happy-little-girl-playing-with-colorful-inflatable-ring-in-outdoor-swimming-pool-on-hot-summer-day-kids-learn-to-swim-child-water-toys-children-play-in-tropical-resort-family-beach-vacation_hxhxlfgxm_thumbnail-1080_01.png` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://img1.taslgs.com/upload/vod/2020-05/2020-05-07/2020050711.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://thumbs.theync.com/thumbs/7/1/4/7/4/71474958878c04968e9.mp4/71474958878c04968e9.mp4-1.jpg` |
| +1 | \|\|celebjihad.com^$3p | -- | en.av4.xyz | 3 | image | `https://celebjihad.com/wp-content/uploads/2019/04/t_mila_kunis_nude_webcam_video2.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://dojki-porn.name/uploads/posts/2020-11/1606137335_001.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://static.thisav.com/images/videothumbs/311335-1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://thumbs.theync.com/thumbs/5/2/0/3/1/52031459d2122be382b.mp4/52031459d2122be382b.mp4-3.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://blog-imgs-109.fc2.com/a/v/s/avstory/h05231.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://dm0qx8t0i9gc9.cloudfront.net/thumbnails/video/MPaEbz-/videoblocks-close-up-shot-of-little-girl-sitting-on-bench-in-dressing-room-and-putting-on-ballet-shoes-when-preparing-for-dance-class_r8opc5vwx_thumbnail-1080_01.png` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://wild-kitty.net/video/vid183.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://img.redwap-cdn.com/222/222566/222566_320x180.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://extra.famegirls.net/content2/8077/thumb100.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://fi1-ph.ypncdn.com/videos/202007/25/335981022/original/14(m=e8KSKgaaaa)(mh=BqES9AkA1d2BKd5h).jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.xlesbian.club/images/thumbs/a/25405/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.xlesbian.club/images/thumbs/a/42614/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://rapefilms.net/tb/mastrubation-from-mom.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://rapefilms.net/tb/the-first-sex-exp.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.xlesbian.club/images/thumbs/a/42821/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://yhrcdn.com/video/bnp/bnp2-hd.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://image.tmdb.org/t/p/original/2AI3pSt5sbAEav6isVDIeCuiZql.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.xlesbian.club/images/thumbs/a/47939/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://dm0qx8t0i9gc9.cloudfront.net/thumbnails/video/V__xp7pUe/mom-dad-and-their-cute-young-daughter-relaxing-together-at-home-facing-at-the-camera-with-happy-friendly-smiles_b8yfylck_thumbnail-1080_01.png` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://panchirasakasa.xyz/wp-content/uploads/2021/05/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88-2021-05-29-12.43.51.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://s2.bitporno.com/thumb/0/200703/202GGDN55YQWJQEVYDBOM.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://porno18.blog.br/thumbs/nonude-com-novinha-pelada.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.pinimg.com/736x/ac/25/db/ac25db0aaea89c35590b18ab983f11b1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.xlesbian.club/images/thumbs/a/40474/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://s4.bitporno.com/thumb/0/201006/431GJFQKUOBGXWDPBXOHP.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://i.xlesbian.club/images/thumbs/a/52462/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://thumbs.theync.com/thumbs/2/0/2/4/9/2024925c93b4f0de6a7.mp4/2024925c93b4f0de6a7.mp4-3.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://eiga.k-img.com/images/movie/50251/photo/60320c7422d884d0/640.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://www.nudeclap.com/images/91/brothers-fucking-sisters-and-mothers-hd.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://okashik.atype.jp/images/106-taskj-043/1.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://extra.famegirls.net/content2/8085/thumb100.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://s4.bitporno.com/thumb/0/200703/201GGDN44O6GV9WBOZ89L.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://media.porn.se/thumbs/5/f/d/2/d/5fd2d843e4f6d/5fd2d843e4f6d.4.3.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://tb.sb-cd.com/t/3927259/3/9/w:500/t4-enh/girlrimming-sex-and-rimming.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `https://www.nudeclap.com/images/10/hot-girls-naked-teens-hd.jpg` |
| +1 |  |  | en.av4.xyz | 3 | image | `http://cacrip.nakadashi.pw/AV4.us.jpg` |
| +1 | /favicon.ico$image,3p,domain=~streameast.live\|~apple.com\|~douban.com\|~bahn.de\|~winfuture.de\|~bt.com\|~ebay.com.au\|~ebay.com\|~ebay.co.uk\|~go.com\|~github.com\|~microsoft.com\|~stackexchange.com\|~stackoverflow.com\|~askubuntu.com\|~reddit.com\|~4chan.org\|~twitter.com\|~live.com\|~espn.com\|~yahoo.com\|~jit.si | -- | en.av4.xyz | 3 | image | `https://twitter.com/favicon.ico` |
| +1 | \|\|js.gazo.space/index.php?js=*&advertisement&$script | -- | en.av4.xyz | 3 | script | `https://js.gazo.space/index.php?js=av4&advertisement&` |
| +1 |  |  | en.av4.xyz | 3 | script | `https://js.gazo.space/index.php?js=very` |
| +0 |  |  | en.av4.xyz | 1 | doc | `http://en.av4.xyz/` |
</details>

<details><summary>Logger output (||jpg4.pw^)</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +0 |  |  | d3ddbc9c-ab4e-440d-8a46-ac0b7bcf167c.moz-extension-scheme | 3 | image | `http://de.nyuu.info/favicon.ico` |
| +0 | \|\|jpg4.pw^ | -- | cndata.jpg4.pw | 1 | doc | `http://cndata.jpg4.pw/index.php?oldhot=all` |
| +0 | /favicon.ico$image,3p,domain=~streameast.live\|~apple.com\|~douban.com\|~bahn.de\|~winfuture.de\|~bt.com\|~ebay.com.au\|~ebay.com\|~ebay.co.uk\|~go.com\|~github.com\|~microsoft.com\|~stackexchange.com\|~stackoverflow.com\|~askubuntu.com\|~reddit.com\|~4chan.org\|~twitter.com\|~live.com\|~espn.com\|~yahoo.com\|~jit.si | -- | de.nyuu.info | 3 | image | `https://twitter.com/favicon.ico` |
| +0 | \|\|js.gazo.space/index.php?js=*&advertisement&$script | -- | de.nyuu.info | 3 | script | `https://js.gazo.space/index.php?js=av4&advertisement&` |
| +0 |  |  | de.nyuu.info | 3 | image | `http://cacrip.nakadashi.pw/AV4.us.jpg` |
| +0 | /favicon.ico$image,3p,domain=~streameast.live\|~apple.com\|~douban.com\|~bahn.de\|~winfuture.de\|~bt.com\|~ebay.com.au\|~ebay.com\|~ebay.co.uk\|~go.com\|~github.com\|~microsoft.com\|~stackexchange.com\|~stackoverflow.com\|~askubuntu.com\|~reddit.com\|~4chan.org\|~twitter.com\|~live.com\|~espn.com\|~yahoo.com\|~jit.si | -- | de.nyuu.info | 3 | image | `https://twitter.com/favicon.ico` |
| +0 | \|\|js.gazo.space/index.php?js=*&advertisement&$script | -- | de.nyuu.info | 3 | script | `https://js.gazo.space/index.php?js=av4&advertisement&` |
| +0 |  |  | de.nyuu.info | 3 | script | `https://js.gazo.space/index.php?js=very` |
| +0 |  |  | de.nyuu.info | 1 | doc | `http://de.nyuu.info/ch/pornhub` |
</details>

**Comment by Jeromeyheibrr** [comment]
Hey

**Pull request closed without merging**
